### ISSUE TITLE
”rotate_iou2d_calculator.py“ file is missing from the \mmrotate\models\task_modules\assigners

### ISSUE THREAD

**Issue by leaves801** [Haru-zt/DDPLS#6]
Traceback (most recent call last):
  File "tools/train.py", line 135, in <module>
    main()
  File "tools/train.py", line 71, in main
    register_all_modules(init_default_scope=False)
  File "/root/autodl-tmp/DDPLS-main/mmrotate/utils/setup_env.py", line 21, in register_all_modules
    import mmrotate.models  # noqa: F401,F403
  File "/root/autodl-tmp/DDPLS-main/mmrotate/models/__init__.py", line 9, in <module>
    from .task_modules import *  # noqa: F401,F403
  File "/root/autodl-tmp/DDPLS-main/mmrotate/models/task_modules/__init__.py", line 2, in <module>
    from .assigners import *  # noqa: F401,F403
  File "/root/autodl-tmp/DDPLS-main/mmrotate/models/task_modules/assigners/__init__.py", line 4, in <module>
    from .rotate_iou2d_calculator import (FakeRBboxOverlaps2D,
ModuleNotFoundError: No module named 'mmrotate.models.task_modules.assigners.rotate_iou2d_calculator'

**Comment by Haru-zt** [comment]
it seems the same problem.&nbsp; i have checked the readme to make sure that the process is correct. maybe you can provide more detail information.



---Original---
From: ***@***.***&gt;
Date: Sun, Nov 24, 2024 16:12 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Haru-zt/DDPLS] ”rotate_iou2d_calculator.py“ file is missing from the \mmrotate\models\task_modules\assigners (Issue #6)




 
Traceback (most recent call last):
 File "tools/train.py", line 135, in 
 main()
 File "tools/train.py", line 71, in main
 register_all_modules(init_default_scope=False)
 File "/root/autodl-tmp/DDPLS-main/mmrotate/utils/setup_env.py", line 21, in register_all_modules
 import mmrotate.models  # noqa: F401,F403
 File "/root/autodl-tmp/DDPLS-main/mmrotate/models/init.py", line 9, in 
 from .task_modules import *  # noqa: F401,F403
 File "/root/autodl-tmp/DDPLS-main/mmrotate/models/task_modules/init.py", line 2, in 
 from .assigners import *  # noqa: F401,F403
 File "/root/autodl-tmp/DDPLS-main/mmrotate/models/task_modules/assigners/init.py", line 4, in 
 from .rotate_iou2d_calculator import (FakeRBboxOverlaps2D,
 ModuleNotFoundError: No module named 'mmrotate.models.task_modules.assigners.rotate_iou2d_calculator'

**Comment by clanguagesh** [comment]
do you solve this problem? i encoutered the same issue

**Comment by Haru-zt** [comment]
I hope this message finds you well. I recently discovered that, due to network issues during the initial upload of the project, a small portion of the files—specifically related to the mmrotate repository—was unfortunately not included in the repository. I sincerely apologize for this oversight and any inconvenience it may have caused.

As some of you may have already addressed this issue on your own by directly referencing or correcting the missing parts from mmrotate, I truly appreciate your effort and understanding. To ensure everyone has access to the complete project, I have thoroughly reviewed and corrected the repository. The missing files have now been added, and the project should be fully functional.

Please feel free to reach out if you encounter any further problems or have questions. Thank you for using this project, and I hope it serves you well.
